name: aiao-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - tensorflow
  - keras
  - seaborn
  - jupyter
  - ipykernel
  - pip
  - pip:
    - scikeras